# EXAMPLE AVERT NODE CONFIG FILE

data_archive = "/home/user/data"

[metadata]
site_code = "NODE"
site_code_extension = ""
ip_extension = ""
longitude = -3.202113
latitude =  55.950803
elevation = ""
timezone = "America/New_York"
vnum = ""
owner = "The AVERT project at Lamont-Doherty Earth Observatory"
owner_contact = "avert-system@proton.me"

[network]
user = "user"
pass = "user"

[relay]
ip = "169.254.2.30"
radio = 4

[telemetry]
transceiver_ip = "192.168.18.101"
target_ip = "192.168.18.110"
telemeter_by = "radio"

[components.seismic]
ip = "192.168.18.102"
model = "centaur"
network_code = "LD"
site_code = "NODE1"
location_code = ""
channel_codes = ["BHZ", "BHN", "BHE"]
archive_format = "{datetime.year}/{network}/{station}/{channel}.{stream_type}"
file_format = "{network}.{station}.{location}.{channel}.{stream_type}.{datetime.year}-{jday:03d}_{datetime.hour:02d}{datetime.minute:02d}.m"
soh_channel_codes = ["LCE", "LCQ", "VDT", "VEC", "VEI", "VM1", "VM2", "VM3"]
timestep = 20

[components.magnetic]
ip = "192.168.18.102"
model = "centaur"
network_code = "LD"
site_code = "NODE1"
location_code = ""
channel_codes = ["LFZ", "LFN", "LFE"]
archive_format = "{datetime.year}/{network}/{station}/{channel}.{stream_type}"
file_format = "{network}.{station}.{location}.{channel}.{stream_type}.{datetime.year}-{jday:03d}_{datetime.hour:02d}{datetime.minute:02d}.m"
timestep = 60

[components.gas]
model = "vaisala-gmp343"
port = "/dev/ttymxc4"
baudrate = 19200
sample_n = 10
archive_format = "{datetime.year}/{station}"
file_format = "{station}.{datetime.year}.{jday:03d}.CO2.csv"

[components.geodetic]
ip = "192.168.18.103"
model = "resolute_polar"
site_code = "HUB1"
port = 80
archive_format = "hourly/raw/{datetime.year}/{jday:03d}/{station}"
file_format = "{station}00US_S_{datetime.year}{jday:03d}{datetime.hour:02d}{datetime.minute:02d}_{rate}_M{mtype}.sbf"
serial_number = 367
rate = "01H_30S"
mtype = 0
